parameters:
  test_authentication_provider_bundle_frontend_token_provider_users:
    'user@example.com': 'password'

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Tests\Services\ApplicationClient\ClientFactory:
    public: true

  SmartAssert\SymfonyTestClient\SymfonyClient:
    public: true
